version: '3'

tasks:
  test:
    desc: Run all Bats tests in shell/bin/lib/tests
    dir: ./bin/lib/tests
    cmds:
      - bats *.bats

  setup:
    desc: Setup the development environment
    cmds:
      - echo "Setting up the development environment..."