warns = ["clippy::all", "clippy::pedantic"]
allow = [
  "clippy::module_name_repetitions",
  "clippy::missing_errors_doc",
  "clippy::missing_panics_doc"
]
deny = ["clippy::unwrap_used", "clippy::expect_used"]
