---
disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - force_try
  - identifier_name

opt_in_rules:
  - attributes
  - closure_spacing
  - empty_enum_arguments
  - explicit_init
  - file_header
  - first_where
  - implicit_return
  - private_outlet

included:
  - Sources
  - Tests

excluded:
  - Carthage
  - Pods
  - Vendor
  - node_modules
  - .build
  - .git
  - .swiftlint.yml

reporter: xcode
